version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: exchange_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: b7Mg4UmK
      PGDATA: '/var/postgresql/data/pgdata'

  marketprice:
    build: ./marketprice
    env_file:
      - marketprice/.env
    volumes:
      - ./marketprice:/var/marketprice/www
    ports:
      - "3000:3000"
    networks:
      - main-networks
    restart: always
    command: npm run dev

  matchengine:
    build: ./matchengine
    env_file:
      - matchengine/.env
    volumes:
      - ./matchengine:/var/matchengine/www
    ports:
      - "3001:3001"
    networks:
      - main-networks
    restart: always
    command: npm run dev

  readhistory:
    build: ./readhistory
    env_file:
      - readhistory/.env
    volumes:
      - ./readhistory:/var/readhistory/www
    ports:
      - "3002:3002"
    networks:
      - main-networks
    restart: always
    command: npm run dev

volumes:
  pg-dataset:
networks:
  main-networks:
    driver: bridge
  