-- CREATE TABLE markets_config (
--     "id"             SERIAL PRIMARY KEY,
--     "unique_id"      uuid NOT NULL,
--     "market_id"      uuid NOT NULL,
--     "market"         VARCHAR(8) NOT NULL,
--     "stock"          VARCHAR(4) NOT NULL,
--     "money"          VARCHAR(4) NOT NULL
-- );
